---
- hosts: hosts_to_add_key
  name: Install_and_run_Apache_web_server
  become: yes
  become_user: root
  handlers:

  tasks:

   - name: Ansible yum install docker
     yum:
       name: docker
       state: present

   - name: Install Docker sdk for python
     pip:
        name: docker    

   - name: Ensure docker deamon is running
     service:
       name: docker
       state: started
  
   - name: webpage directory
     file:
       state: directory
       dest: "/root/webpage"

   - name: Pull httpd docker image
     docker_image:
       name: httpd
       tag: latest
       source: pull

   - name: Copy website to the host
     copy:
       src: index.html
       dest: /root/webpage

   - name: Run docker container
     docker_container:
       name: WebServer
       image: httpd:latest
       state: started
       exposed_ports:
       - "80"
       ports:
       - "80:80"
       volumes:
       - /root/webpage/:/usr/local/apache2/htdocs/


       
